M48
; DRILL file {KiCad 7.0.7} date Sat Aug 26 23:34:53 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-26T23:34:53+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0079
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0394
%
G90
G05
T1
X6.0248Y-3.1
X6.0248Y-3.1512
X6.0248Y-3.2024
X6.1Y-3.1
X6.1Y-3.1512
X6.1Y-3.2024
T2
X6.1334Y-3.1918
X6.1606Y-3.3
X6.1825Y-3.1908
X6.2Y-3.3
X6.2028Y-3.0927
X6.3Y-3.4
T3
X5.7Y-3.3
X5.8Y-3.3
X5.9Y-3.5
X6.0Y-3.5
T4
X6.5Y-3.0
X6.5Y-3.1
X6.5Y-3.2
T0
M30
